/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace v1 {
  export namespace types {
    export namespace common {
      // tslint:disable-next-line:no-empty-interface
      export interface Empty {}
    }
  }
}
