/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace v1 {
  export namespace types {
    export namespace filtering {
      // Enum representing filter operators
      export enum FilterOperator {
        // Check for equality
        EQUAL = 0,
        // Check for inequality
        NOT_EQUAL = 1,
        // Check for greater than
        GREATER_THAN = 2,
        // Check for less than
        LESS_THAN = 3,
        // Check if in a list of values
        IN = 4,
        // Check if not in a list of values
        NOT_IN = 5,
        // Check if within a range of values (requires from and to fields)
        BETWEEN = 6,
        // Search by keyword
        SEARCH = 7,
        // Check if field value is null
        IS_NULL = 8,
        // Check if field value is not null
        IS_NOT_NULL = 9,
      }
      // Definition of filter conditions for queries
      export interface Filtering {
        // Name of the field to filter
        field?: string;
        // Operator to apply (EQUAL, GREATER_THAN, LESS_THAN, IN, etc.)
        operator?: filtering.FilterOperator;
        // Value used for single operators (EQUAL, GREATER_THAN, LESS_THAN)
        value?: string;
        // Used for IN operator (values to filter)
        values?: string[];
        // Start value (used for BETWEEN)
        from?: string;
        // End value (used for BETWEEN)
        to?: string;
        // Keyword for search (used for SEARCH)
        keyword?: string;
      }
      export interface SyntheticField {
        fields?: string[];
      }
    }
  }
}
