/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace v1 {
  export namespace types {
    export namespace identifier {
      export interface Identifier {
        id?: string;
      }
      export interface IdentifierList {
        ids?: string[];
      }
    }
  }
}
