/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace v1 {
  export namespace types {
    export namespace operating {
      export interface DeleteOptionResult {
        acknowledged?: boolean;
        deletedCount?: number;
      }
      export interface UpdateOperationResult {
        acknowledged?: boolean;
        matchedCount?: number;
        modifiedCount?: number;
        upsertedCount?: number;
      }
      export interface OperationStatus {
        // Status of the request
        success?: boolean;
        // Response message
        message?: string;
      }
      export interface OperationError {
        errors?: { [key: string]: string };
      }
      export interface NoDataOperationResult {
        status?: operating.OperationStatus;
        error?: operating.OperationError;
      }
    }
  }
}
