/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace v1 {
  export namespace types {
    export namespace paging {
      // Definition of paging (pagination)
      export interface Paging {
        // Current page
        pageNumber?: number;
        // Number of objects per page
        pageSize?: number;
      }
    }
  }
}
