/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace v1 {
  export namespace types {
    export namespace sorting {
      // Enum representing sort directions
      export enum SortDirection {
        // Sort in ascending order
        ASC = 0,
        // Sort in descending order
        DESC = 1,
      }
      // Definition of sort conditions
      export interface Sorting {
        // Name of the field to sort
        field?: string;
        // Sort direction (ASC, DESC)
        direction?: sorting.SortDirection;
      }
    }
  }
}
