name: goup-development-services

x-common: &common_settings
  restart: unless-stopped
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

networks:
  local_bridge:
    driver: bridge
    name: local-bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.1.1

services:
  nginx:
    <<: *common_settings
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    volumes:
      - ./.devcontainer/nginx/http-proxy-header.conf:/etc/nginx/http-proxy-header.conf:ro
      - ./.devcontainer/nginx/http-server.conf:/etc/nginx/http-server.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      local_bridge:
        ipv4_address: 172.18.1.2
    deploy:
      resources:
        limits:
          memory: 64M
