/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace pagination {
  export interface PaginationRequest {
    page?: number;
    pageSize?: number;
  }
  export interface PaginationResponse {
    totalItems?: number;
    totalPages?: number;
    currentPage?: number;
    pageSize?: number;
  }
}
