name: 'Setup project'
description: 'Setup nodejs, pnpm, and install dependencies'
inputs:
  node:
    description: 'Version of node to install'
    required: true
    default: 20
  pnpm:
    description: 'Version of pnpm to install'
    required: true
    default: 9
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}

    - uses: pnpm/action-setup@v3
      with:
        version: ${{inputs.pnpm}}

    - run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      shell: bash

    - uses: actions/cache@v4
      with:
        path: |
          ${{ env.STORE_PATH }}
          node_modules
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-

    - run: pnpm install --frozen-lockfile
      shell: bash
