name: On Push
on:
  push:
    branches: ['main', 'dev']
    paths-ignore:
      - '**/README.md'
      - '.vscode/**/*'
      - '.husky/**/*'
      - '.devcontainer/**/*'

jobs:
  intergration:
    name: Intergration
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nodejs, pnpm, node_modules
        uses: ./.github/actions/setup-project

      - name: Lint
        run: npx nx run-many -t lint

      - name: Test
        run: npx nx run-many -t test

      - name: Build
        run: npx nx run-many -t build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Start external dependencies
        run: docker compose -f docker/local/docker-compose.yml up nginx redis mongodb rabbitmq maildev s3 s3-setup -d --wait

      - name: E2E Test
        run: npx nx run-many -t e2e
